# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wtSxI9u0y-dFeXRoFd7teI5o6pVz3M3r
"""

import numpy as np
import matplotlib.pyplot as plt

# Tasodifiy nuqtalarni yaratamiz
n_points = 100  # Nuqtalar soni
x = np.random.rand(n_points) * 10  # 0 dan 10 gacha tasodifiy x koordinatalari
y = np.random.rand(n_points) * 10  # 0 dan 10 gacha tasodifiy y koordinatalari

# Scatter grafikni chizamiz
plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='blue', alpha=0.7, edgecolors='k')

# Grafik elementlari
plt.title("Tasodifiy nuqtalar scatter grafigi")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.show()